### ISSUE TITLE
Allow terms to be expressed as either instances or classes

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#113]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on March 20, 2009 13:32:32_

What capability do you want added or improved? 
In voc2RDF, support either instance or class terms 

Where do you want this capability to be accessible? 
In voc2RDF vocabulary creation page. 

What sort of input/command mechanism do you want? 
I think a checkbox that says "create terms as classes, not instances" (with a big help button 
nearby!) should be sufficient, at least at first. (Default is unchecked.)

Alternatively, the capability could be expressed at a term level.  I think this is more of a hierarchy 
situation, and should be addressed as part of a request to handle hierarchies. 

What is the desired output (content, format, location)? If checked, all leaf nodes are classes. 

Other details of your desired capability? 
We need a clear description of when it is appropriate to make your terms into classes.  I *think* 
the main cases are: 
- (a) if your terms will be used to characterize other terms, for example 
ResourceTypes; 
- (b) if you know your terms will primarily be used as part of an inference chain 
with other classes; 
- (c) if you expect to add instances below the classes later.

In general, I think we want to consider the nodes in our vocabularies as terms, meaning 
instances, even if they are higher in a hierarchy than other instances. 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=113_

**Comment by mmisw** [comment]
_From [mike.e.b...@gmail.com](https://code.google.com/u/104806978225310943594/) on October 11, 2010 08:55:42_

Interesting discussion. Has this been resolved? What are the pros and cons of defining terms as instances versus classes, and how does that affect how we bring in ontologies using upload and voc2rdf? Should we set up our csv files differently or will this be handled in the import?

**Comment by mmisw** [comment]
_From [mike.e.b...@gmail.com](https://code.google.com/u/104806978225310943594/) on October 11, 2010 09:23:30_

I suppose that if terms are defined as instances, then the relationships between terms would need to be through mapping using VINE or similar tools rather than through the subClassOf mechanism (?).

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 10:54:21_

Answering Mike's long-ago question, the feature continues to be worth prioritizing, but there is not an urgent need for it. 

The reason you want terms is if the concepts are expressly not sub-classible -- an individual sensor can't have a sub-classed sensor, and an individual term in a vocabulary can't have a sub-classed term, these are stand-alone one-time entities. And SKOS is made to map those kinds of entities, unlike for example the OWL relation sameAs.

The reason you want classes is if you are creating a set of ontological concepts that you do want to be able to sub-class, or use properties that imply sub-class relations. (I *think* that makes semantic web sense....)

In the OWL 1 days these decisions had to be made up front, because an instance could not be a class and vice-versa. In OWL 2, things are more relaxed, although it still isn't entirely free to make an entity both an instance and a class. 

The reason that this is not a higher priority is that typically, people who want classes can build ontologies themselves very well, thank you. So we're crossing the boundary from providing simple vocabulary entry services, to providing ontology building services. That gets complicated fast, and the space has lots of players. This would just be a convenience function for the rare case.

Setting the priority to Low.

**Owner:** jbgrayb...@mindspring.com  
  **Labels:** -Priority-Medium Priority-Low

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:08:33_

**Owner:** grayb...@marinemetadata.org

**Comment by carueda** [comment]
Marking as "xdomes" after taking a look.

The only immediate comment I have now is that voc2rdf has been supposed to facilitate creation of _basic_ vocabularies, and in fact, for a long time, it has only supported a few of the SKOS mapping relations. Before considering any generalization of the tool (eg., by also supporting additional properties like subClassOf), we should perhaps continue to stick with the simple approach of, "let those cases be handled externally with more appropriate tools like Protege, TopBraid, etc.)

**Comment by graybeal** [comment]
It is interesting that BioPortal explicitly takes the opposite views, that ontologies generally are made up of classes, and that instances are second-class citizens, or not citizens at all. The BIoPortal approach has been forced to yield somewhat, to satisfy some practitioners who insist on have instances for terms, but BIoPortal is still poor at representing instances. So in some senses, this is a differentiator.

Mike had asked long ago about pros and cons of classes vs instances -- there's considerable information on the web at this point about that. He also said "I suppose that if terms are defined as instances, then the relationships between terms would need to be through mapping using VINE or similar tools rather than through the subClassOf mechanism (?)." Yes, if you use subClassOf, you are working with classes, and you are not working with the mapping tool. At that point, you are likely using an ontology editing tool like Protege, which brings considerable overhead to your task, but also considerable power.

I think voc2rdf, in particular, should not support vocabulary generation via subClassOf or other class relations (in contrast to my earlier suggestion), until we have the resources to truly understand all the implications of doing so.

**Comment by graybeal** [comment]
Closing, since we seem to be in agreement here.
