### ISSUE TITLE
watchdog: automated registration

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#251]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 28, 2010 21:52:01_

What capability do you want added or improved? automate registration of generated ontology from watchdog program at the ORR.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=251_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 10:36:56_

Is this just about the registration in ORR, or about automatically scheduling the watchdog process?  If the former, I'll create a new task for the latter.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 22, 2014 12:01:31_

This is about the automated registration as an immediate next stage after the conversion process.

The "watchdog" program https://code.google.com/p/mmisw/source/browse/#svn%2Ftrunk%2Forg.mmisw.watchdog is what we have been rewriting with the new repos at github (cf2rdf and udunits2rdf).  

Close this one here?

**Comment by carueda** [comment]
Just to note that the mentioned "watchdog" program has long been obsoleted by the new efforts:
- https://github.com/mmisw/cf2rdf
- https://github.com/mmisw/udunits2rdf

The automated registration itself remains unresolved and probably not to be addressed in this particular project; we also have one other effort, https://github.com/mmisw/orr-ont, where support for this feature is much better (via RESTful endpoint with improved authentication/authorization capability).

**Comment by carueda** [comment]
Decided to close this entry as it's rather vague/confusing (my fault). For example, we have never had or planned to have (AFAICR) a "watchdog process" intended to harvest vocabularies out there in an automated fashion (if that's what perhaps was the initial idea). Our original "watchdog" code was basically just about conversion of some community vocabularies to RDF, a process that is triggered manually. This old code was superseded by the `cf2rdf` and `udunits2rdf` projects mentioned before. In terms of registration, there's also some code developed for OOI (not exercised for a long time now), which is now likely going to be superseded by the `orr-ont` project.

**Comment by graybeal** [comment]
Beg to differ on this one. I always thought the most important thing ORR could have is a watchdog, but I never could find the time (mine or yours) to do it. It is still the most important function ORR could have to be credible maintainer of rehosted content. (To keep up with changes in that content as they happen.)

**Comment by carueda** [comment]
"the most important function ORR could have to be credible maintainer of rehosted content"  -- Sorry, I was not aware of this opinion (to be clear, in terms of automated monitoring/harvesting/registration..).

**Comment by carueda** [comment]
@graybeal : do you still think this is needed as part of the ORR itself?  IMO this should be addressed by individual maintainers of the re-hosted entries (which could perfectly be ourselves as people). For example, https://github.com/mmisw/cf2rdf could incorporate some functionality to monitor the original vocabulary and perform the submission of any updates against the MMI ORR automatically.

**Comment by carueda** [comment]
To complement my opinion:
- Imposing that responsibility to the ORR itself would be too complicated given the potential of highly  disparate original sources for the re-hosted ontologies. And I'm pretty sure we don't want to include case-by-case pieces of code in the ORR to handle the monitoring/autoregistration, etc.
- Additionally, we have been making the ORR software more generally usable and re-deployable so any such custom pieces of monitoring/autoregistration would likely be irrelevant for any other deployments.

**Comment by graybeal** [comment]
I think it is quite valuable, but would not say it is a hard requirement. 

If we want ORR to be used by organizations to manage significant number of ontologies, then it is an important feature. BioPortal has it and keeps many ontologies current that way -- ontologies that otherwise a person would have to be monitoring, or custom software written for each one. _That_ seems like a waste of time.  (The only thing that BioPortal does is, if there is an ontology source URL and the autoupdate flag is set, BioPortal downloads it and checks to see if it has changed since the last one. If so, BioPortal imports it.)

The direction ORR has gone so far is small community service. (If I had it to do over again, I might have pushed the original repository hard in the direction of acquiring more ontologies and vocabularies -- I think that collection is a significant part of BioPortal's reputation and therefore success.) Given ORR is used for smaller communities in a more casual way, maybe the niche doesn't call for this feature. I'd still really want it personally, as a sometimes-user/operator, but not require it as a Project Lead.

**Comment by carueda** [comment]
"Transferring" this to https://github.com/mmisw/orr-ont/issues/41
