### ISSUE TITLE
Example of SKOS: closeMatch vs. SKOS: relatedMatch when mapping

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#255]
_From [steph_wa...@consolidated.net](https://code.google.com/u/112846428158176258467/) on June 14, 2010 13:56:08_

What capability do you want added or improved? 
concrete examples of SKOS: closeMatch and relatedMatch when you "rollover" these function buttons in the "create mapping" mode 

Where do you want this capability to be accessible? 
see above 

What sort of input/command mechanism do you want? 
see above 

What is the desired output (content, format, location)? 

Other details of your desired capability? 
Many people trying to develop mapping files may not know the distinction between closeMatch and relatedMatch and will need some concrete examples to help direct them on which function to choose. 

What version of the product are you using? Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=255_

**Comment by carueda** [comment]
I'm closing this one without any specific changes in the code, and noting that the UI has included tooltips for the various mapping relation buttons, for example:

![image](https://cloud.githubusercontent.com/assets/556505/11454870/719fd8a4-95f4-11e5-90d1-83ba44943aa6.png)

![image](https://cloud.githubusercontent.com/assets/556505/11454874/833393b2-95f4-11e5-84be-4784b4f5d380.png)

which perhaps were not there when this issue was entered.
