### ISSUE TITLE
metadata source selection on upload implementation not quite right

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#329]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on October 06, 2014 15:15:12_

What steps will reproduce the problem? 
1. Get an existing ontology, e.g., http://mmisw.org/orr/#http://mmisw.org/ont/mmitest/udunits2-prefixes 
2. Modify <omv:version> property (problems might be the same with other properties too)
3. Submit ontology in replacement of previous
4. Choose replace original attributes with attributes in uploaded file, click Next. 

What is the expected output/behavior? 
The "Metadata values from the two sources" pop-up should 
- (a) have 3 columns, 
- (b) have a row with a red exclamation point in it (because the Note on the previous screen said there was one common metadata attribute with different, non-blank values).

What do you see instead?  
(See attached screenshot.)
(a) There are only 2 columns.
(b) No row has a red exclamation point. 

What version of the product are you using? (You can see the version at the bottom of the ORR page.) ORR Portal 2.1.1 (201408221430)

 If relevant, please attach the file you were working on (for submission of new ontology, text for import in the vocabulary interface, etc.).

 If possible and relevant, please provide a screen shot showing the problem.

 Please provide information about your browser and version (Firefox, Safari, Chrome, IE, etc.), operating system, etc. old version of Chrome

**Attachment:** [Screen Shot 2014-10-06 at 2.59.53 PM.png](http://code.google.com/p/mmisw/issues/detail?id=329)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=329_

(here's that screenshot:)

![image](https://cloud.githubusercontent.com/assets/556505/8442467/fbb2581a-1f33-11e5-8a2f-6e5e76498036.png)

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 07, 2014 22:48:46_

John: can you please try to reproduce this issue as the fix to issue `#331` is related? I'm not expecting a complete solution for this but probbaly some different behavior in the reporting of the values from the two sources.  (and just to note that the version property is one that the tool handles pretty much by itself, that is, with no much for the user to be able to specifyc the version explicitly).

**Comment by carueda** [comment]
(just pasting the attachment)

![image](https://cloud.githubusercontent.com/assets/556505/8442467/fbb2581a-1f33-11e5-8a2f-6e5e76498036.png)

**Comment by carueda** [comment]
A clarification after looking into this issue more carefully:

> (a) There are only 2 columns.

Actually there are 3 columns: 
![image](https://cloud.githubusercontent.com/assets/556505/11326178/3618e53c-9117-11e5-8f13-c7c36e492d06.png)

What happens is that the UI collapses the two value columns when corresponding values are exactly the same.

> (b) No row has a red exclamation point.

Correct.  (BTW to avoid confusion, this footnote could be avoided when all values are the same.)

Now, the `omv:version` property is *not* included in this details table becasue the tool *always* assigns it automatically -- the user has no ability to specify it directly, even if included in the uploaded file. This has been like this by design.

> previous screen said there was one common metadata attribute with different, non-blank values).

Yes, and this is confusing because is about the `omv:version` property, which, as just said, is special and should not actually be used as a basis for this "diff" analysis.

So, to provide a more consistent handling of this upload operation according to the "design" that has been in place, here is what can be done for this issue:

- make the "diff" analysis be *only* based on properties that can be changed (either from contents in the file or via editing by the user). (In particular, `omv:version` is *not* one of those.)
- only show the `! = Metadata ...` footnote when at least one row in the details table has different values.

**Comment by graybeal** [comment]
Yes, I concur with your analysis and recommended changes, that would be great.
