### ISSUE TITLE
re-hosted handled as fully-hosted?

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#334]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 02, 2014 08:36:02_

What steps will reproduce the problem? 
1. This is related with issue #333 
2. Open http://mmisw.org/ont?uri=http://mmisw.org/testing/CUAHSI/TEST_aquabiocompound 
3. which gets redirected to http://mmisw.org/orr/#http://mmisw.org/testing/CUAHSI/TEST_aquabiocompound 

What is the expected output/behavior?
Normal dispatch on the ontology by URI http://mmisw.org/testing/CUAHSI/TEST_aquabiocompound (just because it appears to be an actual registration) 

What do you see instead? 
Error loading model: Unexpected failure: HTTP/1.1 404 Not Found

What version of the product are you using? (You can see the version at the
bottom of the ORR page.)

MMI Ontology and Term URI Resolver  2.1.3 (201412021018)
ORR Portal 2.1.2 (201410080025)

If possible and relevant, please provide a screen shot showing the problem.

**Attachment:** [2014-12-02_0834.png](http://code.google.com/p/mmisw/issues/detail?id=334)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=334_

**Comment by carueda** [comment]
(just pasting the attachment here)

![image](https://cloud.githubusercontent.com/assets/556505/8442384/9e6806c8-1f33-11e5-84c8-8126269a5017.png)

**Comment by carueda** [comment]
A related observation was captured [here](https://github.com/mmisw/mmiorr/issues/333#issuecomment-71065356),  more specifically:

- http://mmisw.org/testing/CUAHSI/TEST_aquabiocompound 
- http://mmisw.org/CUAHSI/TEST_aquabiocompound

are actually re-hosted entries that happen to follow the MMI URI structure. This seems to trigger the misbehavior of responding with Not-Found.

**Comment by carueda** [comment]
By looking at the *contents* of the ontology via
    http://mmisw.org/ont?form=n3&uri=http://mmisw.org/CUAHSI/TEST_aquabiocompound

note:
```
<http://mmisw.org/ont/CUASHI/TEST_aquabiocompound>
      a       owl:Ontology ;
...
```

That is, there's a discrepancy between the registered URI and the URI of the contained ontology resource:

URI used for | value
--- | --- 
registration | `http://mmisw.org/CUAHSI/TEST_aquabiocompound`  
ontology    | `http://mmisw.org/ont/CUASHI/TEST_aquabiocompound`

Although initial internal resolution between the Portal and the Ont service is fine (that is, using the URI for registration), at some point the internal ontology URI is then taken as the URI for further requests to the Ont server, but this time that request fails because that URI *not* the correct URI of the registration.

An explanation of what might have happened (just a guess):

- Initially the ontology was registered in fully-hosted mode, with the URI `http://mmisw.org/ont/CUASHI/TEST_aquabiocompound`. At this point, no discrepancies at all.
- The ontology was downloaded and later on a new brand new registration was performed with the same contents but in re-hosted mode and with the URI `http://mmisw.org/CUAHSI/TEST_aquabiocompound`  .

Anyways, among the 18 ontologies currently having `CUAHSI` in their names 9and submitted by the same user), these two are the only ones with also `TESTING` in their names. The other 16 seem in good condition (and are fully-hosted BTW). So, I am just simply removing these two problematic entries and closing this issue.
