### ISSUE TITLE
Evaluate MMI ORR services against tests from this paper

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#337]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on January 19, 2015 20:49:43_

What capability do you want added or improved? 
I want the ORR to be tested (ideally with regression tests and/or regular operations tests) in the same ways outlined in this paper: http://aidanhogan.com//docs/epmonitorISWC.pdf . It's a bit dated but has a nice outline of the types of weaknesses of then-current SPARQL implementations. It also points to the following linked data endpoint tester, which uses the CKAN list of endpoints to verify which systems are staying up: http://labs.mondeca.com/sparqlEndpointsStatus/index.html 

Where do you want this capability to be accessible? 
Oh, some sort of administrative/testing interface would be cool. Be nice if the up-time and functional results were visible to users. 

What sort of input/command mechanism do you want? 
Automated execution against new releases and on a regular (weekly?) basis. 

What is the desired output (content, format, location)? 
HTML page would be great. 

Other details of your desired capability? 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=337_

**Comment by carueda** [comment]
@graybeal  I'm closing as "won't fix" because of the brief reason below.  If you disagree, you can of course re-open (or open a new entry in ORR3).

> [paper is] a bit dated but has a nice outline of the types of weaknesses of then-current SPARQL implementations

We are not implementing (and don't intend to implement) any SPARQL endpoint -- we simply use whatever seems appropriate from third-parties (currentlyAllegroGraph). So, why bother? Any monitoring/testing of such an endpoint should probably be done by some other facility, not by the ORR itself.  

> Oh, some sort of administrative/testing interface would be cool. Be nice if the up-time and functional results were visible to users.
> ...
> Automated execution against new releases and on a regular (weekly?) basis.

Wow, too sophisticated for the available resources!
