### ISSUE TITLE
Handling URL fragments in rehosted ontologies

### ISSUE THREAD

**Issue by graybeal** [mmisw/mmiorr#339]
There is a pattern that works for all locally hosted ontologies for creating a term URL: add '/' + the term ID to the URL for the ontology. (It is important to have a pattern, partly because we don't make terms clickable in our displays, so one has to know how to find the term page; but also for people who are just accessing it from scratch using their browser URL.)

This pattern does not work for remotely hosted ontologies that have a base path ending in #, or presumably any other ending except '/'. For those ontologies one has to specify the correct ending in the base path, or even (for the Ont service) `%023` to replace the /.

Would it be possible to redirect queries that have `/term` at the end, if there is a corresponding namespace and term that have a different separator? This would be a much better user experience in many cases.

Of course, it also hides the fact that the wrong URL was used, so a message at the top saying `We have redirected the URL you entered to reflect the base path separator actually used by this remotely hosted ontology (<insert base path separator here>).` at the top of the page. That would be pretty awesome.

(Reference #338 item 2.)

**Comment by carueda** [comment]
>Would it be possible to redirect queries that have /term at the end, if there is a corresponding namespace and term that have a different separator?

Concrete example please?

**Comment by graybeal** [comment]
sorry, takes multiple clicks and so far haven't found one. whatever ontology uses # as its namespace separator (I've seen one or two, but don't know what they were).

**Comment by carueda** [comment]
Perhaps an example would be `http://purl.oclc.org/NET/ssnx/ssn#Precision`?
That is, if the request happens to be with the `/` separator instead of `#`:
- http://mmisw.org/ont?uri=http://purl.oclc.org/NET/ssnx/ssn/Precision

(which does not resolve to any contents because `http://purl.oclc.org/NET/ssnx/ssn/Precision` does not exist in the repository), then actually handle it as if it were with `#`:

- from http://mmisw.org/ont?uri=http://purl.oclc.org/NET/ssnx/ssn%23Precision

If so, I'd say the redirection should only be done in the case of HTML resolution (that is, for human consumption), as doing it also for ontology formats would bring confusion to the client application that made the request ..

**Comment by graybeal** [comment]
yes, exactly so in all respects

**Comment by carueda** [comment]
Closing as "won't fix". If really needed, open issue in relevant new ORR3 repo.
