### ISSUE TITLE
can't unregister udunits test vocabs

### ISSUE THREAD

**Issue by graybeal** [mmisw/mmiorr#348]
I was just trying to unregister the [mmitest UDUnits vocabularies](http://mmisw.org/orr/#so/mmitest/udunits) (originally entered by Carlos) by hitting the unregister button, but so far they aren't disappearing from the list.

Entered the reload command to see if that would help. No dice.

Haven't looked at any details more closely yet.

**Comment by carueda** [comment]
This worked just fine for me.  I did the unregister for `http://mmisw.org/ont/mmitest/udunits2-prefixes`. 
Right after the confirmation dialog, the list gets updated: in my case with the entry not showing up there anymore because it was the last and only version available. I think you actually did complete your unregistration, but there remained one other version available (the 'unregister' command only unregisters one version at at time.)

BTW I went ahead and unregistered *all* the versions of the other 4 `mmitest/udunits2...` entries.
